version: '3.8'

services:
  backend:
    build: .
    command: bash -c "./init.sh"
    container_name: collabothon-api
    volumes:
      - .:/api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

networks:
  default:
    name: app-network
